server:
  port: 18080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #redis配置
  redis:
    database: 10
    host: 192.168.12.205
    port: 6379
    password: hadoop
  datasource:
    #数据库驱动,原始驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.12.205:3306/test_student?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&connectTimeout=6000&socketTimeout=6000
    username: root
    password: kd!253
    druid:
      initialSize: 1 #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      maxActive: 100 #最大连接池数量
      maxWait: 60000 #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      minIdle: 5 #最小连接池数量
      timeBetweenEvictionRunsMillis: 60001
      minEvictableIdleTimeMillis: 300001
      validationQuery: SELECT 'x'
      testWhileIdle: true #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testOnBorrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      poolPreparedStatements: true #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,slf4j
      filter:
        commons-log:
          statement-log-enabled: true
          statement-executable-sql-log-enable: true
        slf4j:
          enabled: true
        stat:
          enabled: true
      stat-view-servlet:
        #指定允许访问监控信息的地址
        allow: 0.0.0.0/0
        #打开SQL监控
        enabled: true

#excel:
#  tmp_path: /tmp/import/
#  download_path: /download/

base:
  global-response:
    enabled: true

#swagger在线文档配置
swagger:
  enabled: true
  ## 需要排除的URL
  exclude-path: /error
  ## 分组
  docket:
    base-v1:
      ## swagger扫描的基础包，默认：全扫描
      base-package: com.lian.base.web.v1
      title: BaseProject接口_V1
      description: BaseProject在线文档
      version: 1.0





